import * as M from '../js/model.js';
import * as E from '../js/estimate.js';

let pass = 0, fail = 0;
const ok = (n, c, x = '') => { if (c) { pass++; console.log('  ✓', n); } else { fail++; console.log('  ✗', n, x); } };
const approx = (a, b, t = 1e-6) => Math.abs(a - b) <= t;

const settings = {
  maxHr: 190, restHr: 45, trimpB: 1.92, gender: 'male', age: 34,
  rpeToReserve: { base: 0.4, slope: 0.05 },
  defaultReserveBySport: { swim: 0.7, bike: 0.65, run: 0.72, strength: 0.5, other: 0.6 },
  cssSpeed: 1.0, runThresholdSpeed: 3.7, ctlDays: 42, atlDays: 7, seedCtl: 0, seedAtl: 0,
  loadBasis: 'trimp', defaultWeightKg: 75, zoneModel: 'lthr',
  imSwimFactor: 1.06, imBikeTargetKmh: 0, imBikeIF: 0.7, imRunFactor: 1.10, transitionsMin: 8,
  weightEconomyPct: 1.0, raceBaselineWeight: 0,
};

console.log('energy model');
const e1 = M.activityEnergy({ sport: 'run', durationSec: 3600, avgHr: 150 }, settings, 75);
// Keytel male: (-55.0969 + 0.6309*150 + 0.1988*75 + 0.2017*34)/4.184 kcal/min * 60
const kexp = ((-55.0969 + 0.6309 * 150 + 0.1988 * 75 + 0.2017 * 34) / 4.184) * 60;
ok('Keytel kcal matches formula', approx(e1, kexp, 1e-6), `${e1} vs ${kexp}`);
ok('heavier athlete burns more', M.activityEnergy({ sport: 'run', durationSec: 3600, avgHr: 150 }, settings, 90) > e1);
ok('MET fallback when no HR', M.activityEnergy({ sport: 'run', durationSec: 3600, rpe: 6 }, settings, 75) > 0);
ok('zero duration -> 0 kcal', M.activityEnergy({ sport: 'run', durationSec: 0, avgHr: 150 }, settings, 75) === 0);

console.log('weight interpolation + trend');
const weights = [{ date: '2026-08-01', kg: 80 }, { date: '2026-08-10', kg: 79 }, { date: '2026-08-20', kg: 78 }];
const wOn = M.weightInterpolator(weights);
ok('carry-forward before next entry', wOn('2026-08-05') === 80);
ok('exact date', wOn('2026-08-10') === 79);
ok('latest after last', wOn('2026-08-25') === 78);
const wt = M.weightTrend(weights, 10);
ok('trend has smoothed series', wt.series.length > 0 && wt.smooth != null);
ok('downward trend => positive drop%', wt.dropPct7 >= -0.01);

console.log('load basis switch (energy)');
const acts = [{ sport: 'run', durationSec: 3600, avgHr: 150, startTime: '2026-08-15T09:00' }];
const pTr = M.performanceChart(acts, settings, { start: '2026-08-15', end: '2026-08-15', basis: 'trimp', weights });
const pEn = M.performanceChart(acts, settings, { start: '2026-08-15', end: '2026-08-15', basis: 'energy', weights });
const wActDay = M.weightInterpolator(weights)('2026-08-15'); // 79kg (carry-forward from 08-10)
const eActDay = M.activityEnergy(acts[0], settings, wActDay);
ok('energy basis load = kcal at that day\'s weight', approx(pEn[0].load, eActDay, 1e-6), `${pEn[0].load} vs ${eActDay}`);
ok('trimp basis differs from energy', Math.abs(pTr[0].load - pEn[0].load) > 1);

console.log('linear fit core (solve3 / OLS)');
const c = E._internal.solve3([[2, 0, 0], [0, 3, 0], [0, 0, 5]], [4, 9, 10]);
ok('solve3 diagonal', approx(c[0], 2) && approx(c[1], 3) && approx(c[2], 2));
// exact linear data => r2 = 1 and recovered coefficients
const rows = [], ys = [];
for (let i = 0; i < 20; i++) { const ctl = i, atl = i % 5; rows.push([1, ctl, -atl]); ys.push(3 + 1.5 * ctl - 0.8 * atl); }
const fit = E._internal.fitLinear(rows, ys);
ok('OLS recovers intercept', approx(fit.coef[0], 3, 1e-6), fit.coef[0]);
ok('OLS recovers k1', approx(fit.coef[1], 1.5, 1e-6), fit.coef[1]);
ok('OLS recovers k2', approx(fit.coef[2], 0.8, 1e-6), fit.coef[2]);
ok('OLS r2 = 1 for exact data', approx(fit.r2, 1, 1e-9), fit.r2);

console.log('impulse-response recovery (grid search finds planted τ)');
// plant a performance signal generated by a known model, recover τ1,τ2 via grid
const N = 200; const load = [];
for (let i = 0; i < N; i++) load.push(40 + 40 * Math.sin(i / 9) + (i % 7 === 0 ? 60 : 0));
const TRUE1 = 40, TRUE2 = 8, K1 = 2.0, K2 = 1.3, A = 1.0;
const ctlT = E._internal.ewmaSeries(load, TRUE1), atlT = E._internal.ewmaSeries(load, TRUE2);
const yTrue = [], gridRows = [];
const sampleDays = [];
for (let i = 30; i < N; i += 3) { sampleDays.push(i); yTrue.push(A + K1 * ctlT[i] - K2 * atlT[i]); }
let best = null;
for (let t1 = 20; t1 <= 56; t1 += 4) {
  const ctl = E._internal.ewmaSeries(load, t1);
  for (let t2 = 4; t2 <= 16; t2 += 2) {
    const atl = E._internal.ewmaSeries(load, t2);
    const R = sampleDays.map(i => [1, ctl[i], -atl[i]]);
    const f = E._internal.fitLinear(R, yTrue);
    if (!f || f.coef[1] < 0 || f.coef[2] < 0) continue;
    if (!best || f.r2 > best.r2) best = { t1, t2, r2: f.r2 };
  }
}
ok('recovers fitness τ within grid step', Math.abs(best.t1 - TRUE1) <= 4, `got ${best.t1}`);
ok('recovers fatigue τ within grid step', Math.abs(best.t2 - TRUE2) <= 2, `got ${best.t2}`);
ok('recovery r2 ~ 1', best.r2 > 0.98, best.r2);

console.log('threshold estimation from history + tests');
const hist = [];
let d = '2026-06-01';
for (let i = 0; i < 40; i++) {
  const sp = ['swim', 'bike', 'run'][i % 3];
  const spd = sp === 'swim' ? 0.95 + (i % 5) * 0.01 : sp === 'run' ? 3.3 + (i % 5) * 0.05 : 8 + (i % 5) * 0.2;
  hist.push({ sport: sp, startTime: d + 'T09:00', durationSec: 25 * 60, avgHr: 150 + (i % 6), maxHr: 178 + (i % 8), avgSpeed: spd, distanceM: spd * 25 * 60 });
  d = M.addDays(d, 1);
}
const tests = [{ id: 't1', type: 'swim_css', date: '2026-07-01', t400: 380, t200: 185 }, { id: 't2', type: 'run_tt20', date: '2026-07-05', distanceM: 4600, avgHr: 176 }];
const est = E.estimateThresholds(hist, tests, settings);
ok('maxHr estimated from data', est.maxHr.value >= 180 && est.maxHr.value <= 190, est.maxHr.value);
ok('CSS from swim test', approx(est.cssSpeed.value, 200 / (380 - 185), 1e-6), est.cssSpeed.value);
ok('CSS marked as test source, high conf', est.cssSpeed.source === 'test' && est.cssSpeed.confidence === 'high');
ok('run threshold from TT (4600m/1200s)', approx(est.runThresholdSpeed.value, 4600 / 1200, 1e-6), est.runThresholdSpeed.value);
ok('LTHR from run TT avg HR', est.lthr.value === 176, est.lthr.value);
ok('zones computed', est.zones.hr.length === 5 && est.zones.runPace.length === 5 && est.zones.swimPace.length === 4);

console.log('calibrate + predict on realistic-ish data');
const cal = E.calibrateModel(hist, settings, []);
ok('calibrate returns a result object', typeof cal.ok === 'boolean');
if (cal.ok) ok('fitted τ in grid bounds', cal.tau1 >= 20 && cal.tau1 <= 56 && cal.tau2 >= 4 && cal.tau2 <= 16, JSON.stringify(cal));
else ok('calibrate degrades gracefully with reason', typeof cal.reason === 'string', cal.reason);

const pmc = M.performanceChart(hist, settings, { weights: [{ date: '2026-06-01', kg: 78 }] });
const pred = E.predict(hist, settings, [{ date: '2026-06-01', kg: 78 }], tests, pmc, est);
ok('predicts run 5k and 10k', pred.efforts.run5k > 0 && pred.efforts.run10k > pred.efforts.run5k, JSON.stringify(pred.efforts));
ok('10k slower per km than 5k (Riegel)', (pred.efforts.run10k / 10) > (pred.efforts.run5k / 5));
ok('Ironman projection has splits + total', pred.ironman && pred.ironman.total > 0 && pred.ironman.swimSec > 0 && pred.ironman.runSec > 0);
ok('IM total = sum of legs + transitions', approx(pred.ironman.total, pred.ironman.swimSec + pred.ironman.bikeSec + pred.ironman.runSec + pred.ironman.transitions, 1e-6));

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
